import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { builtinRules } from "@argus/rules-builtin";
import type { CliIO } from "./io.js";
import { EXIT_ERROR, EXIT_OK } from "./exit-codes.js";

const CONFIG_FILE_NAME = "argus.yaml";

/**
 * Writes a starter `argus.yaml` in the current directory. Refuses to
 * overwrite an existing one (non-destructive: the desired end-state — a config
 * exists — already holds, so this is a success, not an error). The generated
 * file enumerates every built-in rule at its default severity so the catalogue
 * is discoverable from the file itself.
 */
export async function runInit(io: CliIO): Promise<number> {
  const target = path.join(io.cwd, CONFIG_FILE_NAME);

  if (existsSync(target)) {
    io.stderr(`${CONFIG_FILE_NAME} already exists — leaving it untouched.\n`);
    return EXIT_OK;
  }

  try {
    // "wx" fails if the file appeared between the check above and now (TOCTOU-safe).
    await writeFile(target, starterConfig(), { encoding: "utf8", flag: "wx" });
  } catch (cause) {
    if (isErrnoException(cause) && cause.code === "EEXIST") {
      io.stderr(`${CONFIG_FILE_NAME} already exists — leaving it untouched.\n`);
      return EXIT_OK;
    }
    io.stderr(`argus: could not write ${CONFIG_FILE_NAME}: ${errorMessage(cause)}\n`);
    return EXIT_ERROR;
  }

  io.stdout(
    `Created ${CONFIG_FILE_NAME} with ${builtinRules.length} built-in rules at their defaults.\n`,
  );
  return EXIT_OK;
}

/** Builds the starter config text, deriving the rule list from the live catalogue. */
export function starterConfig(): string {
  const ruleLines = builtinRules
    .map((module) => `  ${module.rule.id}: ${module.rule.defaultSeverity}`)
    .join("\n");

  return `# Argus configuration (generated by \`argus init\`).
# Docs: docs/guide/configuration.md · Rule reference: docs/guide/rules.md
#
# Every built-in rule is listed at its default severity. Change a severity
# ("info" | "warning" | "error" | "critical"), set a rule to "off", or use the
# long form  rule-id: { severity: warning, options: { max: 40 } }  to pass
# rule-specific options. Rules omitted here still run at their defaults.

languages:
  - typescript
  - javascript

# Extra glob patterns to skip. node_modules, .git, dist, build, coverage,
# .turbo and .stryker-tmp are always skipped.
ignore: []

rules:
${ruleLines}
`;
}

function isErrnoException(value: unknown): value is NodeJS.ErrnoException {
  return value instanceof Error && "code" in value;
}

function errorMessage(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}
